### ISSUE TITLE
failed compile on ubuntu 16.04

### ISSUE THREAD

**Issue by EugeneBogush** [uNetworking/uSockets#8]
/opt/uSockets$ make
for f in examples/*.c; do gcc -flto -std=c11 -DLIBUS_NO_SSL -O3 -o $(basename "$f" ".c") -Isrc src/*.c src/eventing/*.c "$f"; done
examples/echo_server.c:4:20: fatal error: helper.h: No such file or directory
compilation terminated.
examples/hammer_test.c:4:20: fatal error: helper.h: No such file or directory
compilation terminated.
examples/http_load_test.c:4:20: fatal error: helper.h: No such file or directory
compilation terminated.
examples/http_server.c:4:20: fatal error: helper.h: No such file or directory
compilation terminated.
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1

**Comment by alexhultman** [comment]
Looks like I forgot to track helper.h

**Comment by EugeneBogush** [comment]
Yes. I didn't find this file in project

**Comment by alexhultman** [comment]
I'll track and commit it later today

**Comment by alexhultman** [comment]
Pull now

**Comment by EugeneBogush** [comment]
yes
